name: gaming-graphics-core22
adopt-info: debs
summary: Shared Mesa stack for gaming
description: |
 This snap includes newer versions of Mesa optimized for gaming.
confinement: strict
grade: stable
base: core22
compression: lzo

slots:
  gaming-mesa:
    interface: content
    read:
      - /

package-repositories:
  - type: apt
    url: http://archive.ubuntu.com/ubuntu/
    suites: [jammy, jammy-updates]
    components: [main, universe]
    architectures: [amd64, i386]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    key-server: keyserver.ubuntu.com
  - type: apt
    # FIXME: We need to enable both 32-bit and 64-bit architectures
    # for this PPA, but Snapcraft doesn't let us do that with the
    # short syntax. So use the full version instead.

    # ppa: oibaf/graphics-drivers
    url: http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu
    suites: [jammy]
    components: [main]
    architectures: [amd64, i386]
    key-id: 5ABCE68FF4633EA42E219156957D2708A03A4626
    key-server: keyserver.ubuntu.com

parts:
  debs:
    plugin: nil
    stage-packages:
      - libgl1-mesa-glx:i386
      - libgl1-mesa-glx:amd64
      - libgl1-mesa-dri:i386
      - libgl1-mesa-dri:amd64
      - libvkd3d1:i386
      - libvkd3d1:amd64
      - libvulkan1:i386
      - libvulkan1:amd64
      - mesa-va-drivers:amd64
      - mesa-va-drivers:i386
      - mesa-vdpau-drivers:amd64
      - mesa-vdpau-drivers:i386
      - mesa-vulkan-drivers:amd64
      - mesa-vulkan-drivers:i386
      - va-driver-all:amd64
      - va-driver-all:i386
      - va-driver:i386
      - libvdpau-va-gl1:amd64
      - libxml2:i386
      - libxml2:amd64
      - libdrm-common
      - vulkan-tools # For testing/debugging
      - mesa-utils # For testing/debugging
    stage:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/gcc
      - -usr/share/mesa-demos
      - -usr/share/lintian
      - -usr/share/X11
      - -usr/share/bug
      - -usr/share/locale
      - -usr/share/gdb
      - -etc/X11
      - -etc/sensors3.conf
      - -usr/lib/*/gconv
    override-prime: |
      craftctl default
      # Set the snap version from the mesa package version
      craftctl set version=$(dpkg-parsechangelog -l $CRAFT_PART_INSTALL/usr/share/doc/mesa-va-drivers/changelog.gz -S Version | cut -c -32)
